import { Button, Header, Input, PasswordInput, TextInput } from "@mantine/core";
import Head from "next/head";
import Link from "next/link";
import styles from "./styles.module.css";

const Dashboard = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className={styles.header} bg="blue.6" height={80}>
        <Link className={styles.active} href={"/dashboard"}>
          Venda
        </Link>
        <Link href={"/dashboard/deliveryman"}>Entregador</Link>
        <Link href={"/dashboard/product"}>Produtos</Link>
        <Link href={"/"}>Sair</Link>
      </Header>
      <main className={styles.containerProduct}>
        <div className={styles.tableStyle}>
          <Button
            component={Link}
            href="/dashboard/create"
            color="blue"
            size="md"
          >
            Adicionar
          </Button>
        </div>
      </main>
    </div>
  );
};

export default Dashboard;
