import { Header } from "@mantine/core";
import Cookies from "js-cookie";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { GetServerSidePropsContext } from "next/types";
import styles from "./styles.module.css";

interface IHomeProps {
  isLogged: boolean;
  userName?: string;
}

export default function Home({ isLogged, userName }: IHomeProps) {
  const handleLogout = async () => {
    Cookies.remove("userName");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header className={styles.header} bg="blue.6" height={80}>
        <Link href={"/"}>Sobre a Loja</Link>
        {isLogged ? (
          <>
            <Link href={"/dashboard"}>dashboard</Link>
            <Link href={"/login"} onClick={handleLogout}>
              Logout
            </Link>
          </>
        ) : (
          <>
            <Link href={"/login"}>Login</Link>
            <Link href={"/register"}>Registrar</Link>
          </>
        )}
      </Header>
      <div className={styles.userName}>
        {isLogged && <p>Seja bem vindo {userName}!!!</p>}
      </div>
      {isLogged && (
        <Image
          className={styles.image}
          src="/cremosinho.png"
          alt="Picture of the author"
          width={250}
          height={250}
        />
      )}
    </div>
  );
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const { userName } = ctx.req.cookies;
  if (userName) {
    return {
      props: {
        isLogged: true,
        userName,
      },
    };
  }
  return {
    props: {
      isLogged: false,
    },
  };
}
