import { Header } from "@mantine/core";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "./styles.module.css";

export default function Home() {
  const isLogged = true;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className={styles.header} height={80} bg={'blue'}>
        <Link href={'/'}>
          Sobre a Loja 
        </Link> 
        {isLogged ? (

          <Link href={'/dashboard'}>
            Dashboard
          </Link >

        ) : (
          <>
            <Link href={'/login'}>
              Login 
            </Link >
            <Link href={'/register'}>
              Registrar
            </Link>
          </>)
        }
      </Header>
    </div>
  );
}
