import { Header } from "@mantine/core";
import Head from "next/head";
import Link from "next/link";
import styles from "./styles.module.css";

const Dashboard = () => {
    const isLogged = true;
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header className={styles.header} height={80} bg={'blue'}>
                <Link className={styles.active} href={'/sale'}>
                    Venda
                </Link >

                <Link href={'/deliveryman'}>
                    Entregador
                </Link >
                <Link href={'/dashboard/product'}>
                    Produtos
                </Link>
                <Link href={'/'}>
                    Sair
                </Link>

            </Header>
        </div>
    );
}


export default Dashboard;